---
title: "BI510_Final"
format: html
editor: visual
---

# Loading Packages
```{r}
library(curl)
library(tidyverse)
library(dplyr)
library(devtools)
devtools::install_github("ricardo-bion/ggradar", dependencies = TRUE)
library(ggradar) # for radar plots
library(ggalt) # for dumbbell plots
```

# Load Data
```{r}
f_UnscheduledData <- curl("https://raw.githubusercontent.com/sadams32/BI510-Final/refs/heads/main/UnscheduledData.csv") 

d_UnscheduledData <- read.csv(f_UnscheduledData, header = TRUE, sep = ",", stringsAsFactors = TRUE) # read in data

colnames(d_UnscheduledData) <- c("Category", "Summary_Statistic", "Black", "White")

head(d_UnscheduledData) # preview
```

# Heatmap
```{r}
# Pivot longer
data_unscheduled_long <- d_UnscheduledData %>%
  pivot_longer(cols = c(Black, White), 
               names_to = "Race", 
               values_to = "Value")

data_unscheduled_long <- data_unscheduled_long %>%
  filter(Summary_Statistic != "Observations")
```

```{r}
HeatMap <- ggplot(data_unscheduled_long, aes(x = Race, y = `Summary_Statistic`, fill = Value)) +
  geom_tile(color = "white") +
  facet_wrap(~ Category, scales = "free_y", ncol = 1) +
  scale_fill_gradient(low = "lightyellow", high = "red", trans = "log") +
  theme_minimal() +
  labs(title = "Heatmap with Log Color Scale",
       x = "Maternal Race",
       y = "Summary Statistic",
       fill = "Value") +
  theme(axis.text.y = element_text(size = 6))

ggsave("HeatMap.png", plot = HeatMap, width = 7, height = 4)
```

# Radar Plot
```{r}
radar_data <- data_unscheduled_long %>%
  filter(Summary_Statistic %in% c(
    "Medicaid",
    "Less than BA",
    "BA or graduate degree",
    "Married"
  ))

radar_data <- radar_data %>%
  pivot_wider(names_from = Summary_Statistic, values_from = Value)

radar_data <- radar_data %>%
  select(-Category)

radarplot <- ggradar(radar_data,
        values.radar = c(0, 0.5, 1),
        grid.min = 0, 
        grid.mid = 0.5, 
        grid.max = 1,
        group.line.width = 1.5,
        group.point.size = 3,
        axis.label.size = 3,
        legend.text.size = 10)

ggsave("radarplot.png", plot = radarplot, width = 7, height = 4)
```

# Line Plot
```{r}
unscheduled_clean <- d_UnscheduledData %>%
  filter(Category %in% c(
    "C-section rates", 
    "Maternal and infant health",
    "Mother sociodemographic characteristics",
    "Attendant physician characteristics"
  )) %>%
  mutate(Summary_Statistic = factor(Summary_Statistic, levels = unique(Summary_Statistic))) # keep order

lineplot <- ggplot(unscheduled_clean, aes(y = Summary_Statistic)) +
  # Draw line between Black and White an subject data
  geom_segment(aes(x = Black, xend = White, yend = Summary_Statistic), color = "grey", size = 1) +
  geom_point(aes(x = Black, color = "Black"), size = 3) +
  geom_point(aes(x = White, color = "White"), size = 3) +
  
  # Set custom colors
  scale_color_manual(values = c("Black" = "red", "White" = "blue")) +
  
  labs(
    title = "Black vs White Patients: Unscheduled Deliveries",
    x = "Proportion",
    y = "",
    color = "Group"
  ) +
  theme_minimal(base_family = "Times") +
  theme(
    plot.title = element_text(size = 14, face = "bold"),
    axis.text.y = element_text(size = 10)
  )

ggsave("lineplot.png", plot = lineplot, width = 7, height = 4)
```
